In [5]:
import numpy
import torch

In [11]:
d = torch.rand(4,3,2,2)
print(d)

tensor([[[[7.0088e-02, 5.4411e-01],
          [1.5614e-01, 5.4402e-01]],

         [[2.1278e-01, 6.7651e-01],
          [2.1740e-01, 5.4520e-04]],

         [[6.2553e-01, 4.1478e-01],
          [5.4899e-01, 2.6189e-02]]],


        [[[8.5494e-01, 3.7160e-01],
          [8.8028e-01, 3.4913e-01]],

         [[1.6463e-01, 7.1440e-01],
          [8.4501e-01, 8.9042e-01]],

         [[6.4149e-01, 5.9404e-01],
          [6.3455e-01, 7.3410e-01]]],


        [[[2.8943e-01, 3.3791e-01],
          [1.9303e-01, 5.2475e-01]],

         [[1.9472e-01, 8.3129e-01],
          [1.3181e-01, 6.4388e-01]],

         [[5.8378e-01, 1.7016e-01],
          [3.8702e-01, 8.1579e-01]]],


        [[[6.4811e-01, 4.2878e-01],
          [1.7878e-01, 4.1410e-01]],

         [[9.5440e-01, 5.1953e-01],
          [4.1501e-01, 6.1072e-01]],

         [[2.2875e-01, 1.0662e-01],
          [7.7653e-01, 2.3136e-02]]]])


In [13]:
mask = torch.triu(torch.ones(2, 2), diagonal=1)
mask

tensor([[0., 1.],
        [0., 0.]])

In [18]:
d.masked_fill(mask.bool(), -torch.inf)

tensor([[[[7.0088e-02,       -inf],
          [1.5614e-01, 5.4402e-01]],

         [[2.1278e-01,       -inf],
          [2.1740e-01, 5.4520e-04]],

         [[6.2553e-01,       -inf],
          [5.4899e-01, 2.6189e-02]]],


        [[[8.5494e-01,       -inf],
          [8.8028e-01, 3.4913e-01]],

         [[1.6463e-01,       -inf],
          [8.4501e-01, 8.9042e-01]],

         [[6.4149e-01,       -inf],
          [6.3455e-01, 7.3410e-01]]],


        [[[2.8943e-01,       -inf],
          [1.9303e-01, 5.2475e-01]],

         [[1.9472e-01,       -inf],
          [1.3181e-01, 6.4388e-01]],

         [[5.8378e-01,       -inf],
          [3.8702e-01, 8.1579e-01]]],


        [[[6.4811e-01,       -inf],
          [1.7878e-01, 4.1410e-01]],

         [[9.5440e-01,       -inf],
          [4.1501e-01, 6.1072e-01]],

         [[2.2875e-01,       -inf],
          [7.7653e-01, 2.3136e-02]]]])